/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.organizations.uad.anonymizer;

import com.liferay.organizations.uad.constants.OrganizationsUADConstants;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.Organization;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.service.OrganizationLocalService;

import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

import java.util.Arrays;
import java.util.List;

/**
 * Provides the base implementation for the organization UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link OrganizationUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseOrganizationUADAnonymizer
	extends DynamicQueryUADAnonymizer<Organization> {
	@Override
	public void autoAnonymize(Organization organization, long userId,
		User anonymousUser) throws PortalException {
		if (organization.getUserId() == userId) {
			organization.setUserId(anonymousUser.getUserId());
			organization.setUserName(anonymousUser.getFullName());
		}

		organizationLocalService.updateOrganization(organization);
	}

	@Override
	public void delete(Organization organization) throws PortalException {
		organizationLocalService.deleteOrganization(organization);
	}

	@Override
	public List<String> getNonanonymizableFieldNames() {
		return Arrays.asList();
	}

	@Override
	public Class<Organization> getTypeClass() {
		return Organization.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return organizationLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return OrganizationsUADConstants.USER_ID_FIELD_NAMES_ORGANIZATION;
	}

	@Reference
	protected OrganizationLocalService organizationLocalService;
}