/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.asset.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.change.tracking.CTModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AssetVocabularyDepotEntryRel service. Represents a row in the &quot;AssetVocabularyDepotEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.asset.model.impl.AssetVocabularyDepotEntryRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.asset.model.impl.AssetVocabularyDepotEntryRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetVocabularyDepotEntryRel
 * @generated
 */
@ProviderType
public interface AssetVocabularyDepotEntryRelModel
	extends BaseModel<AssetVocabularyDepotEntryRel>,
			CTModel<AssetVocabularyDepotEntryRel>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset vocabulary depot entry rel model instance should use the {@link AssetVocabularyDepotEntryRel} interface instead.
	 */

	/**
	 * Returns the primary key of this asset vocabulary depot entry rel.
	 *
	 * @return the primary key of this asset vocabulary depot entry rel
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset vocabulary depot entry rel.
	 *
	 * @param primaryKey the primary key of this asset vocabulary depot entry rel
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this asset vocabulary depot entry rel.
	 *
	 * @return the mvcc version of this asset vocabulary depot entry rel
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this asset vocabulary depot entry rel.
	 *
	 * @param mvccVersion the mvcc version of this asset vocabulary depot entry rel
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ct collection ID of this asset vocabulary depot entry rel.
	 *
	 * @return the ct collection ID of this asset vocabulary depot entry rel
	 */
	@Override
	public long getCtCollectionId();

	/**
	 * Sets the ct collection ID of this asset vocabulary depot entry rel.
	 *
	 * @param ctCollectionId the ct collection ID of this asset vocabulary depot entry rel
	 */
	@Override
	public void setCtCollectionId(long ctCollectionId);

	/**
	 * Returns the uuid of this asset vocabulary depot entry rel.
	 *
	 * @return the uuid of this asset vocabulary depot entry rel
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this asset vocabulary depot entry rel.
	 *
	 * @param uuid the uuid of this asset vocabulary depot entry rel
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the asset vocabulary depot entry rel ID of this asset vocabulary depot entry rel.
	 *
	 * @return the asset vocabulary depot entry rel ID of this asset vocabulary depot entry rel
	 */
	public long getAssetVocabularyDepotEntryRelId();

	/**
	 * Sets the asset vocabulary depot entry rel ID of this asset vocabulary depot entry rel.
	 *
	 * @param assetVocabularyDepotEntryRelId the asset vocabulary depot entry rel ID of this asset vocabulary depot entry rel
	 */
	public void setAssetVocabularyDepotEntryRelId(
		long assetVocabularyDepotEntryRelId);

	/**
	 * Returns the company ID of this asset vocabulary depot entry rel.
	 *
	 * @return the company ID of this asset vocabulary depot entry rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset vocabulary depot entry rel.
	 *
	 * @param companyId the company ID of this asset vocabulary depot entry rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the asset vocabulary ID of this asset vocabulary depot entry rel.
	 *
	 * @return the asset vocabulary ID of this asset vocabulary depot entry rel
	 */
	public long getAssetVocabularyId();

	/**
	 * Sets the asset vocabulary ID of this asset vocabulary depot entry rel.
	 *
	 * @param assetVocabularyId the asset vocabulary ID of this asset vocabulary depot entry rel
	 */
	public void setAssetVocabularyId(long assetVocabularyId);

	/**
	 * Returns the depot entry ID of this asset vocabulary depot entry rel.
	 *
	 * @return the depot entry ID of this asset vocabulary depot entry rel
	 */
	public long getDepotEntryId();

	/**
	 * Sets the depot entry ID of this asset vocabulary depot entry rel.
	 *
	 * @param depotEntryId the depot entry ID of this asset vocabulary depot entry rel
	 */
	public void setDepotEntryId(long depotEntryId);

	@Override
	public AssetVocabularyDepotEntryRel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}