/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.asset.model.impl;

import com.liferay.asset.model.AssetVocabularyDepotEntryRel;
import com.liferay.asset.model.AssetVocabularyDepotEntryRelModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AssetVocabularyDepotEntryRel service. Represents a row in the &quot;AssetVocabularyDepotEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssetVocabularyDepotEntryRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetVocabularyDepotEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetVocabularyDepotEntryRelImpl
 * @generated
 */
@JSON(strict = true)
public class AssetVocabularyDepotEntryRelModelImpl
	extends BaseModelImpl<AssetVocabularyDepotEntryRel>
	implements AssetVocabularyDepotEntryRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset vocabulary depot entry rel model instance should use the <code>AssetVocabularyDepotEntryRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "AssetVocabularyDepotEntryRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR},
		{"assetVocabularyDepotEntryRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"assetVocabularyId", Types.BIGINT},
		{"depotEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assetVocabularyDepotEntryRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetVocabularyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("depotEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AssetVocabularyDepotEntryRel (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,assetVocabularyDepotEntryRelId LONG not null,companyId LONG,assetVocabularyId LONG,depotEntryId LONG,primary key (assetVocabularyDepotEntryRelId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table AssetVocabularyDepotEntryRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY assetVocabularyDepotEntryRel.assetVocabularyDepotEntryRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AssetVocabularyDepotEntryRel.assetVocabularyDepotEntryRelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETVOCABULARYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEPOTENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETVOCABULARYDEPOTENTRYRELID_COLUMN_BITMASK =
		16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AssetVocabularyDepotEntryRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetVocabularyDepotEntryRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetVocabularyDepotEntryRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetVocabularyDepotEntryRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetVocabularyDepotEntryRel.class;
	}

	@Override
	public String getModelClassName() {
		return AssetVocabularyDepotEntryRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AssetVocabularyDepotEntryRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AssetVocabularyDepotEntryRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetVocabularyDepotEntryRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(AssetVocabularyDepotEntryRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AssetVocabularyDepotEntryRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AssetVocabularyDepotEntryRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AssetVocabularyDepotEntryRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AssetVocabularyDepotEntryRel, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AssetVocabularyDepotEntryRel, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AssetVocabularyDepotEntryRel, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AssetVocabularyDepotEntryRel, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<AssetVocabularyDepotEntryRel, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", AssetVocabularyDepotEntryRel::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId",
				AssetVocabularyDepotEntryRel::getCtCollectionId);
			attributeGetterFunctions.put(
				"uuid", AssetVocabularyDepotEntryRel::getUuid);
			attributeGetterFunctions.put(
				"assetVocabularyDepotEntryRelId",
				AssetVocabularyDepotEntryRel::
					getAssetVocabularyDepotEntryRelId);
			attributeGetterFunctions.put(
				"companyId", AssetVocabularyDepotEntryRel::getCompanyId);
			attributeGetterFunctions.put(
				"assetVocabularyId",
				AssetVocabularyDepotEntryRel::getAssetVocabularyId);
			attributeGetterFunctions.put(
				"depotEntryId", AssetVocabularyDepotEntryRel::getDepotEntryId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AssetVocabularyDepotEntryRel, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AssetVocabularyDepotEntryRel, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AssetVocabularyDepotEntryRel, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<AssetVocabularyDepotEntryRel, Long>)
					AssetVocabularyDepotEntryRel::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<AssetVocabularyDepotEntryRel, Long>)
					AssetVocabularyDepotEntryRel::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AssetVocabularyDepotEntryRel, String>)
					AssetVocabularyDepotEntryRel::setUuid);
			attributeSetterBiConsumers.put(
				"assetVocabularyDepotEntryRelId",
				(BiConsumer<AssetVocabularyDepotEntryRel, Long>)
					AssetVocabularyDepotEntryRel::
						setAssetVocabularyDepotEntryRelId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AssetVocabularyDepotEntryRel, Long>)
					AssetVocabularyDepotEntryRel::setCompanyId);
			attributeSetterBiConsumers.put(
				"assetVocabularyId",
				(BiConsumer<AssetVocabularyDepotEntryRel, Long>)
					AssetVocabularyDepotEntryRel::setAssetVocabularyId);
			attributeSetterBiConsumers.put(
				"depotEntryId",
				(BiConsumer<AssetVocabularyDepotEntryRel, Long>)
					AssetVocabularyDepotEntryRel::setDepotEntryId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAssetVocabularyDepotEntryRelId() {
		return _assetVocabularyDepotEntryRelId;
	}

	@Override
	public void setAssetVocabularyDepotEntryRelId(
		long assetVocabularyDepotEntryRelId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetVocabularyDepotEntryRelId = assetVocabularyDepotEntryRelId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getAssetVocabularyId() {
		return _assetVocabularyId;
	}

	@Override
	public void setAssetVocabularyId(long assetVocabularyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetVocabularyId = assetVocabularyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAssetVocabularyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("assetVocabularyId"));
	}

	@JSON
	@Override
	public long getDepotEntryId() {
		return _depotEntryId;
	}

	@Override
	public void setDepotEntryId(long depotEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_depotEntryId = depotEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDepotEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("depotEntryId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AssetVocabularyDepotEntryRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetVocabularyDepotEntryRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AssetVocabularyDepotEntryRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetVocabularyDepotEntryRelImpl assetVocabularyDepotEntryRelImpl =
			new AssetVocabularyDepotEntryRelImpl();

		assetVocabularyDepotEntryRelImpl.setMvccVersion(getMvccVersion());
		assetVocabularyDepotEntryRelImpl.setCtCollectionId(getCtCollectionId());
		assetVocabularyDepotEntryRelImpl.setUuid(getUuid());
		assetVocabularyDepotEntryRelImpl.setAssetVocabularyDepotEntryRelId(
			getAssetVocabularyDepotEntryRelId());
		assetVocabularyDepotEntryRelImpl.setCompanyId(getCompanyId());
		assetVocabularyDepotEntryRelImpl.setAssetVocabularyId(
			getAssetVocabularyId());
		assetVocabularyDepotEntryRelImpl.setDepotEntryId(getDepotEntryId());

		assetVocabularyDepotEntryRelImpl.resetOriginalValues();

		return assetVocabularyDepotEntryRelImpl;
	}

	@Override
	public AssetVocabularyDepotEntryRel cloneWithOriginalValues() {
		AssetVocabularyDepotEntryRelImpl assetVocabularyDepotEntryRelImpl =
			new AssetVocabularyDepotEntryRelImpl();

		assetVocabularyDepotEntryRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		assetVocabularyDepotEntryRelImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		assetVocabularyDepotEntryRelImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		assetVocabularyDepotEntryRelImpl.setAssetVocabularyDepotEntryRelId(
			this.<Long>getColumnOriginalValue(
				"assetVocabularyDepotEntryRelId"));
		assetVocabularyDepotEntryRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		assetVocabularyDepotEntryRelImpl.setAssetVocabularyId(
			this.<Long>getColumnOriginalValue("assetVocabularyId"));
		assetVocabularyDepotEntryRelImpl.setDepotEntryId(
			this.<Long>getColumnOriginalValue("depotEntryId"));

		return assetVocabularyDepotEntryRelImpl;
	}

	@Override
	public int compareTo(
		AssetVocabularyDepotEntryRel assetVocabularyDepotEntryRel) {

		long primaryKey = assetVocabularyDepotEntryRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AssetVocabularyDepotEntryRel)) {
			return false;
		}

		AssetVocabularyDepotEntryRel assetVocabularyDepotEntryRel =
			(AssetVocabularyDepotEntryRel)object;

		long primaryKey = assetVocabularyDepotEntryRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetVocabularyDepotEntryRel> toCacheModel() {
		AssetVocabularyDepotEntryRelCacheModel
			assetVocabularyDepotEntryRelCacheModel =
				new AssetVocabularyDepotEntryRelCacheModel();

		assetVocabularyDepotEntryRelCacheModel.mvccVersion = getMvccVersion();

		assetVocabularyDepotEntryRelCacheModel.ctCollectionId =
			getCtCollectionId();

		assetVocabularyDepotEntryRelCacheModel.uuid = getUuid();

		String uuid = assetVocabularyDepotEntryRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assetVocabularyDepotEntryRelCacheModel.uuid = null;
		}

		assetVocabularyDepotEntryRelCacheModel.assetVocabularyDepotEntryRelId =
			getAssetVocabularyDepotEntryRelId();

		assetVocabularyDepotEntryRelCacheModel.companyId = getCompanyId();

		assetVocabularyDepotEntryRelCacheModel.assetVocabularyId =
			getAssetVocabularyId();

		assetVocabularyDepotEntryRelCacheModel.depotEntryId = getDepotEntryId();

		return assetVocabularyDepotEntryRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AssetVocabularyDepotEntryRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AssetVocabularyDepotEntryRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetVocabularyDepotEntryRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AssetVocabularyDepotEntryRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, AssetVocabularyDepotEntryRel>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						AssetVocabularyDepotEntryRel.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _assetVocabularyDepotEntryRelId;
	private long _companyId;
	private long _assetVocabularyId;
	private long _depotEntryId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AssetVocabularyDepotEntryRel, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AssetVocabularyDepotEntryRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"assetVocabularyDepotEntryRelId", _assetVocabularyDepotEntryRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("assetVocabularyId", _assetVocabularyId);
		_columnOriginalValues.put("depotEntryId", _depotEntryId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("assetVocabularyDepotEntryRelId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("assetVocabularyId", 32L);

		columnBitmasks.put("depotEntryId", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AssetVocabularyDepotEntryRel _escapedModel;

}