/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.asset.model.impl;

import com.liferay.asset.model.AssetVocabularyDepotEntryRel;
import com.liferay.asset.service.AssetVocabularyDepotEntryRelLocalServiceUtil;

/**
 * The extended model base implementation for the AssetVocabularyDepotEntryRel service. Represents a row in the &quot;AssetVocabularyDepotEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetVocabularyDepotEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetVocabularyDepotEntryRelImpl
 * @see AssetVocabularyDepotEntryRel
 * @generated
 */
public abstract class AssetVocabularyDepotEntryRelBaseImpl
	extends AssetVocabularyDepotEntryRelModelImpl
	implements AssetVocabularyDepotEntryRel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset vocabulary depot entry rel model instance should use the <code>AssetVocabularyDepotEntryRel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AssetVocabularyDepotEntryRelLocalServiceUtil.
				addAssetVocabularyDepotEntryRel(this);
		}
		else {
			AssetVocabularyDepotEntryRelLocalServiceUtil.
				updateAssetVocabularyDepotEntryRel(this);
		}
	}

}