/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.asset.service.base;

import com.liferay.asset.model.AssetVocabularyDepotEntryRel;
import com.liferay.asset.service.AssetVocabularyDepotEntryRelLocalService;
import com.liferay.asset.service.persistence.AssetVocabularyDepotEntryRelPersistence;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.change.tracking.CTService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the asset vocabulary depot entry rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.service.impl.AssetVocabularyDepotEntryRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.service.impl.AssetVocabularyDepotEntryRelLocalServiceImpl
 * @generated
 */
public abstract class AssetVocabularyDepotEntryRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, AssetVocabularyDepotEntryRelLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AssetVocabularyDepotEntryRelLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.asset.service.AssetVocabularyDepotEntryRelLocalServiceUtil</code>.
	 */

	/**
	 * Adds the asset vocabulary depot entry rel to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyDepotEntryRel the asset vocabulary depot entry rel
	 * @return the asset vocabulary depot entry rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetVocabularyDepotEntryRel addAssetVocabularyDepotEntryRel(
		AssetVocabularyDepotEntryRel assetVocabularyDepotEntryRel) {

		assetVocabularyDepotEntryRel.setNew(true);

		return assetVocabularyDepotEntryRelPersistence.update(
			assetVocabularyDepotEntryRel);
	}

	/**
	 * Creates a new asset vocabulary depot entry rel with the primary key. Does not add the asset vocabulary depot entry rel to the database.
	 *
	 * @param assetVocabularyDepotEntryRelId the primary key for the new asset vocabulary depot entry rel
	 * @return the new asset vocabulary depot entry rel
	 */
	@Override
	@Transactional(enabled = false)
	public AssetVocabularyDepotEntryRel createAssetVocabularyDepotEntryRel(
		long assetVocabularyDepotEntryRelId) {

		return assetVocabularyDepotEntryRelPersistence.create(
			assetVocabularyDepotEntryRelId);
	}

	/**
	 * Deletes the asset vocabulary depot entry rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyDepotEntryRelId the primary key of the asset vocabulary depot entry rel
	 * @return the asset vocabulary depot entry rel that was removed
	 * @throws PortalException if a asset vocabulary depot entry rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetVocabularyDepotEntryRel deleteAssetVocabularyDepotEntryRel(
			long assetVocabularyDepotEntryRelId)
		throws PortalException {

		return assetVocabularyDepotEntryRelPersistence.remove(
			assetVocabularyDepotEntryRelId);
	}

	/**
	 * Deletes the asset vocabulary depot entry rel from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyDepotEntryRel the asset vocabulary depot entry rel
	 * @return the asset vocabulary depot entry rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetVocabularyDepotEntryRel deleteAssetVocabularyDepotEntryRel(
		AssetVocabularyDepotEntryRel assetVocabularyDepotEntryRel) {

		return assetVocabularyDepotEntryRelPersistence.remove(
			assetVocabularyDepotEntryRel);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return assetVocabularyDepotEntryRelPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AssetVocabularyDepotEntryRel.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetVocabularyDepotEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.asset.model.impl.AssetVocabularyDepotEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return assetVocabularyDepotEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.asset.model.impl.AssetVocabularyDepotEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return assetVocabularyDepotEntryRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetVocabularyDepotEntryRelPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return assetVocabularyDepotEntryRelPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AssetVocabularyDepotEntryRel fetchAssetVocabularyDepotEntryRel(
		long assetVocabularyDepotEntryRelId) {

		return assetVocabularyDepotEntryRelPersistence.fetchByPrimaryKey(
			assetVocabularyDepotEntryRelId);
	}

	/**
	 * Returns the asset vocabulary depot entry rel with the matching UUID and company.
	 *
	 * @param uuid the asset vocabulary depot entry rel's UUID
	 * @param companyId the primary key of the company
	 * @return the matching asset vocabulary depot entry rel, or <code>null</code> if a matching asset vocabulary depot entry rel could not be found
	 */
	@Override
	public AssetVocabularyDepotEntryRel
		fetchAssetVocabularyDepotEntryRelByUuidAndCompanyId(
			String uuid, long companyId) {

		return assetVocabularyDepotEntryRelPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the asset vocabulary depot entry rel with the primary key.
	 *
	 * @param assetVocabularyDepotEntryRelId the primary key of the asset vocabulary depot entry rel
	 * @return the asset vocabulary depot entry rel
	 * @throws PortalException if a asset vocabulary depot entry rel with the primary key could not be found
	 */
	@Override
	public AssetVocabularyDepotEntryRel getAssetVocabularyDepotEntryRel(
			long assetVocabularyDepotEntryRelId)
		throws PortalException {

		return assetVocabularyDepotEntryRelPersistence.findByPrimaryKey(
			assetVocabularyDepotEntryRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			assetVocabularyDepotEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			AssetVocabularyDepotEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetVocabularyDepotEntryRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			assetVocabularyDepotEntryRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			AssetVocabularyDepotEntryRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetVocabularyDepotEntryRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			assetVocabularyDepotEntryRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			AssetVocabularyDepotEntryRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetVocabularyDepotEntryRelId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetVocabularyDepotEntryRelPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement AssetVocabularyDepotEntryRelLocalServiceImpl#deleteAssetVocabularyDepotEntryRel(AssetVocabularyDepotEntryRel) to avoid orphaned data");
		}

		return assetVocabularyDepotEntryRelLocalService.
			deleteAssetVocabularyDepotEntryRel(
				(AssetVocabularyDepotEntryRel)persistedModel);
	}

	@Override
	public BasePersistence<AssetVocabularyDepotEntryRel> getBasePersistence() {
		return assetVocabularyDepotEntryRelPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return assetVocabularyDepotEntryRelPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns the asset vocabulary depot entry rel with the matching UUID and company.
	 *
	 * @param uuid the asset vocabulary depot entry rel's UUID
	 * @param companyId the primary key of the company
	 * @return the matching asset vocabulary depot entry rel
	 * @throws PortalException if a matching asset vocabulary depot entry rel could not be found
	 */
	@Override
	public AssetVocabularyDepotEntryRel
			getAssetVocabularyDepotEntryRelByUuidAndCompanyId(
				String uuid, long companyId)
		throws PortalException {

		return assetVocabularyDepotEntryRelPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the asset vocabulary depot entry rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.asset.model.impl.AssetVocabularyDepotEntryRelModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset vocabulary depot entry rels
	 * @param end the upper bound of the range of asset vocabulary depot entry rels (not inclusive)
	 * @return the range of asset vocabulary depot entry rels
	 */
	@Override
	public List<AssetVocabularyDepotEntryRel> getAssetVocabularyDepotEntryRels(
		int start, int end) {

		return assetVocabularyDepotEntryRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset vocabulary depot entry rels.
	 *
	 * @return the number of asset vocabulary depot entry rels
	 */
	@Override
	public int getAssetVocabularyDepotEntryRelsCount() {
		return assetVocabularyDepotEntryRelPersistence.countAll();
	}

	/**
	 * Updates the asset vocabulary depot entry rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AssetVocabularyDepotEntryRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param assetVocabularyDepotEntryRel the asset vocabulary depot entry rel
	 * @return the asset vocabulary depot entry rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetVocabularyDepotEntryRel updateAssetVocabularyDepotEntryRel(
		AssetVocabularyDepotEntryRel assetVocabularyDepotEntryRel) {

		return assetVocabularyDepotEntryRelPersistence.update(
			assetVocabularyDepotEntryRel);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AssetVocabularyDepotEntryRelLocalService.class,
			IdentifiableOSGiService.class, CTService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		assetVocabularyDepotEntryRelLocalService =
			(AssetVocabularyDepotEntryRelLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetVocabularyDepotEntryRelLocalService.class.getName();
	}

	@Override
	public CTPersistence<AssetVocabularyDepotEntryRel> getCTPersistence() {
		return assetVocabularyDepotEntryRelPersistence;
	}

	@Override
	public Class<AssetVocabularyDepotEntryRel> getModelClass() {
		return AssetVocabularyDepotEntryRel.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<AssetVocabularyDepotEntryRel>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(
			assetVocabularyDepotEntryRelPersistence);
	}

	protected String getModelClassName() {
		return AssetVocabularyDepotEntryRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			assetVocabularyDepotEntryRelPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected AssetVocabularyDepotEntryRelLocalService
		assetVocabularyDepotEntryRelLocalService;

	@Reference
	protected AssetVocabularyDepotEntryRelPersistence
		assetVocabularyDepotEntryRelPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AssetVocabularyDepotEntryRelLocalServiceBaseImpl.class);

}